version: '3'
services:
  nginx:
    image: nginx:1.19.1
    container_name: codelike_bbs_nginx
    ports:
      - 8090:8090
    depends_on:
      - php
      - db
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/html

  php:
    build: ./php
    container_name: codelike_bbs_php
    depends_on:
      - db
    volumes:
      - ../:/var/www/html
      - ./php/log/:/var/log/php/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.0
    container_name: codelike_bbs_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - db
    ports:
      - 8091:80

  db:
    image: mysql:5.7
    container_name: codelike_bbs_mysql
    ports:
      - 23307:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log/:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
